### ISSUE TITLE
v. 2.1.0 throws 'Could not get frontmost application' error all the time

### ISSUE THREAD

**Issue by Jyqft** [deanishe/alfred-appscripts#2]
With version 2.1.0 of the workflow, summoning the workflow always results in the message 'Could not get frontmost application' being displayed. Prior versions did not have this issue for me.

I tried looking at the workflow's log, which did not contain any Interesting Info. So here's the log for All Information upon summoning the workflow:

    Starting debug for 'AppScripts'

    [STDERR: alfred.workflow.input.scriptfilter] 13:05:18 workflow.py:2140 DEBUG    Workflow version : 2.1.0
    13:05:18 workflow.py:1543 DEBUG    Reading settings from `/Users/<myusername>/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-appscripts/settings.json` ...
    13:05:18 workflow.py:2401 DEBUG    Update check not due
    13:05:18 appscripts.py:117 DEBUG    args : {u'--debug': False,
     u'--help': False,
     u'--quiet': False,
     u'--verbose': False,
     u'--version': False,
     u'<key>': None,
     u'<query>': u'',
     u'config': False,
     u'search': True,
     u'toggle': False,
     u'userpaths': False}
    13:05:18 workflow.py:1778 DEBUG    Loading cached data from : /Users/<myusername>/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-appscripts/__workflow_update_status.cpickle
    13:05:18 workflow.py:2349 DEBUG    update_data : {u'available': False}
    13:05:19 appscripts.py:344 ERROR    AppleScript error : dyld: Library not loaded: @rpath/libswiftAppKit.dylib
      Referenced from: /Users/<myusername>/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A0303EFC-4372-4D2B-93D9-81BCF6BF968D/ActiveApp
      Reason: image not found
    13:05:19 workflow.py:2331 DEBUG    Set last run version : 2.1.0
    13:05:19 workflow.py:2176 DEBUG    Workflow finished in 0.232 seconds.
    [INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
    <items><item valid="no"><title>Could not get frontmost application.</title><subtitle /><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

I'm using Alfred 2 v2.8.1 (425) on Mac OS X 10.10.5 (14F1021).

**Comment by deanishe** [comment]
I can't replicate the issue. I've tried to fix it in [v2.2](https://github.com/deanishe/alfred-appscripts/releases/tag/v2.2).

Could you install that version and let me know if it's working again? If not, I'll revert it to the old method.

**Comment by Jyqft** [comment]
The issue I'm experiencing is fixed in v2.2. Thanks.
