### ISSUE TITLE
This workflow was working a week ago, now its completely broken? Help?

### ISSUE THREAD

**Issue by ghost** [deanishe/alfred-appscripts#8]
This very useful workflow was working a week ago and I was running all manner of applescripts in different applications, but after having to reinstall alfred5 and its data recently it has become completely broken and won't even display its configuration settings. Please help.

**Comment by ghost** [comment]
Nevermind.  I downloaded and replaced the most recent release with an old one from 2014 and it works fine now.

**Comment by ghost** [comment]
I've now encountered the same problem and its completely non functional again

**Comment by occludedpixel** [comment]
@tobycarson56 May I know what errors are displayed in the workflow debugger?

By the way, I have just started using this workflow and it also didn't work for me at first. After doing some very rough changes to address the errors from the debugger, it seems to be working for me now though I haven't done any thorough testing. You can check out the changes I made at my fork of this repo.
